name: Tests

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Set environment variables
        run: |
          echo "NODE_ENV=test" >> $GITHUB_ENV
          echo "NODE_OPTIONS=--experimental-vm-modules" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
      - name: Run tests
        run: npm test
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30
      - name: Generate test summary
        run: |
          if [ -f coverage/lcov-report/index.html ]; then
            echo "### Test Coverage Report" >> $GITHUB_STEP_SUMMARY
            echo "Coverage report generated. See uploaded artifact." >> $GITHUB_STEP_SUMMARY
          else
            echo "### Test Results" >> $GITHUB_STEP_SUMMARY
            echo "Tests completed. See logs for details." >> $GITHUB_STEP_SUMMARY
          fi
      - name: Annotate test failures
        if: failure()
        run: echo "::error::Test failures detected. Check logs and coverage report for details."
